# This is a basic workflow that is manually triggered

name: Download workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "42 7 1 * *"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Set environment vars
      run: echo "PULLDATE=$(date +%F)" >> $GITHUB_ENV
    - name: Download data
      run: |
         [ test -f trials.csv ] && rm -f trials.csv
         wget -O trials.csv https://www.socialscienceregistry.org/site/csv
         echo "# Registrations in the AEA RCT Registry (2013-05-15 through ${{ env.PULLDATE }})" > README.md
         echo "" >> README.md
         echo "## Description " >> README.md
         echo "This dataset contains publicly available data on the American Economic Association's RCT registry downloaded on ${{ env.PULLDATE }}." >> README.md
         echo "" >> README.md
         echo "## Subject" >> README.md
         echo "Social Sciences" >> README.md
   # Deploy to a new branch      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: releases
        full_commit_message: "Registrations in the AEA RCT Registry (2013-05-15 through ${{ env.PULLDATE }})"
        tag_name: release-${{ env.PULLDATE }}
        tag_message: "Registrations in the AEA RCT Registry (2013-05-15 through ${{ env.PULLDATE }})"
