# This is a basic workflow that is manually triggered

name: Download workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Download data
      run: |
         [ test -f trials.csv ] && rm -f trials.csv
         wget -O trials.csv https://www.socialscienceregistry.org/site/csv
         echo "# Registrations in the AEA RCT Registry (2013-05-15 through $(date +%F))" > README.md
         echo "" >> README.md
         echo "## Description " >> README.md
         echo "This dataset contains publicly available data on the American Economic Association's RCT registry downloaded on $(date +%F)." >> README.md
         echo "" >> README.md
         echo "## Subject" >> README.md
         echo "Social Sciences" >> README.md
   # Deploy to a new branch      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: release-$(date +%F)
